# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
sort_translit  = true
linemode       = "mtime"
show_hidden    = true

[opener]
edit = [
	{ run = "${EDITOR:-vi} %s", desc = "$EDITOR",      for = "unix", block = true },
	{ run = "code %s",          desc = "code",         for = "windows", orphan = true },
	{ run = "code -w %s",       desc = "code (block)", for = "windows", block = true },
]
play = [
	{ run = "xdg-open %s1", orphan = true, desc = "Play", for = "linux" },
	{ run = "open %s",                     desc = "Play", for = "macos" },
	{ run = 'start "" %s1', orphan = true, desc = "Play", for = "windows" },
	{ run = "termux-open %s1",             desc = "Play", for = "android" },
	{ run = "mediainfo %s1; echo 'Press enter to exit'; read _", block = true, desc = "Show media info", for = "unix" },
	{ run = "mediainfo %s1 & pause", block = true, desc = "Show media info", for = "windows" },
]
open = [
	{ run = "xdg-open %s1",    desc = "Open", for = "linux" },
	{ run = "open %s",         desc = "Open", for = "macos" },
	{ run = 'start "" %s1',    desc = "Open", for = "windows", orphan = true },
	{ run = "termux-open %s1", desc = "Open", for = "android" },
]
reveal = [
	{ run = "xdg-open %d1",         desc = "Reveal", for = "linux" },
	{ run = "open -R %s1",          desc = "Reveal", for = "macos" },
	{ run = "explorer /select,%s1", desc = "Reveal", for = "windows", orphan = true },
	{ run = "termux-open %d1",      desc = "Reveal", for = "android" },
	{ run = "clear; exiftool %s1; echo 'Press enter to exit'; read _", desc = "Show EXIF", for = "unix", block = true },
]
extract = [
	{ run = "ya pub extract --list %s", desc = "Extract here" },
]
download = [
	{ run = "ya emit download --open %S", desc = "Download and open" },
	{ run = "ya emit download %S",        desc = "Download" },
]
