target = "~/.config/wireplumber/wireplumber.conf.d"
exclude = [
    '\.bub\.toml$',
    '^\.git.*$',
    "^(README|LICEN[CS]E|COPYING).*$",
    '\.unboxrc.*$',
]
include = []
link_root = false
link_type = "absolute"
